@echo off
set "DB_HOST=130.61.46.215"
set "DB_PORT=3306
//set "DB_USER=amluser"
//set "DB_PASS=aml2841@fusionX"
set "CONFIG_SERVER_URL=http://132.145.233.0:8080"
set "CONF_SERVER_USR=admin"
set "CONF_SERVER_PASS=trypassword"
set "CONF_ENV_NAME=qa"
set "DB_USER=APP"
set "DB_PASSWORD=JhA64Z*aJ7dv`Ky"
set "COMMON_DB_PASSWORD=#HW[)7\-/nMP3L"
@echo on
echo "DB_HOST: "%DB_HOST%
echo "DB_PORT: "%DB_PORT%
//echo "DB_USER: "%DB_USER%
//echo "DB_PASS: "%DB_PASS%
echo "CONF_URL_PORT: "%CONF_URL_PORT%
echo "CONF_SERVER_USR: "%CONF_SERVER_USR%
echo "CONF_SERVER_PASS: "%CONF_SERVER_PASS%
echo "CONF_ENV_NAME: "%CONF_ENV_NAME%
echo "DB_USER: "%DB_USER%
echo "DB_PASSWORD: "%DB_PASSWORD%
echo "COMMON_DB_PASSWORD: "%COMMON_DB_PASSWORD%
@echo off
 