databaseChangeLog:
- changeSet:
    id: 1
    author: minolid@i360.lk (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            startWith: 1
            constraints:
              primaryKey: true
            name: id
            type: BIGINT
        - column:
            name: code
            type: VARCHAR(45)
        - column:
            name: product_type
            type: VARCHAR(45)
        - column:
            name: product_name
            type: VARCHAR(45)
        - column:
            name: product_description
            type: VARCHAR(45)
        - column:
            name: status
            type: TINYINT(3)
        tableName: product