databaseChangeLog:
  - changeSet:
      id: 1568978666107-31
      author: Minoli (generated)
      changes:
        - createTable:
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                  name: id
                  type: BIGINT
              - column:
                  constraints:
                    nullable: false
                  name: customer
                  type: BIGINT
              - column:
                  name: risk
                  type: DOUBLE
            tableName: product_risk