apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aml-risk-autoscaller
  namespace: fusionx-aml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aml-risk
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 80